Write-Output ""
Write-Output "Command					Description"
Write-Output "------------------------------------------------------------------------------"
Write-Output "SearchIn <string>			Search inside files for text"
Write-Output "GT <name>				Quick Change Directory command"
Write-Output "Touch					Create File"
Write-Output "Publish					Publish .Net Application as RELEASE"
Write-Output "NewGUID					Creates and Displays GUID"
Write-Output "Backup					Starts RoboCopy Backup"
Write-Output "------------------------------------------------------------------------------"
Write-Output ""
